//! Confirms `src/bindings.ts` still matches the Rust structs it is generated
//! from. Every IPC-facing type derives `TS` under `#[cfg(test)]` (`ts-rs` is a
//! dev-dependency, so the derive does not exist in a release build); this test
//! is what turns those derives into an enforced contract instead of a hope.
//!
//! Run `UPDATE_BINDINGS=1 cargo test bindings` from `src-tauri/` to regenerate
//! `src/bindings.ts` after changing a struct, then commit the result.

use ts_rs::{Config, TS};

use crate::commands::app::Dashboard;
use crate::commands::checkins::{CheckinRow, EntryCheck, EntryStatus};
use crate::commands::documents::ExpiringDocument;
use crate::commands::expiries::{Expiry, ExpiryKind};
use crate::commands::memberships::RenewalPreview;
use crate::error::{AppError, Reason};
use crate::models::{
    Checkin, Document, DocumentInput, DocumentKind, Filter, Member, MemberDetail, MemberInput,
    MemberRow, Membership, PaymentMethod,
};

const HEADER: &str = "// AUTO-GENERATED by ts-rs — DO NOT EDIT BY HAND.\n\
// Run `cargo test` in src-tauri/ to check this file for drift, or\n\
// `UPDATE_BINDINGS=1 cargo test` from src-tauri/ to regenerate it.\n";

/// `i64` is `bigint` by ts-rs default, but Tauri's IPC carries it as plain
/// JSON, which the frontend has always read as `number` — matching that is
/// not a style choice, it is what the wire actually sends.
fn config() -> Config {
    Config::default().with_large_int("number")
}

macro_rules! declare {
    ($cfg:expr, $out:expr, $($ty:ty),+ $(,)?) => {
        $(
            $out.push_str("export ");
            $out.push_str(&<$ty as TS>::decl($cfg));
            $out.push_str("\n\n");
        )+
    };
}

fn generate() -> String {
    let cfg = &config();
    let mut out = String::from(HEADER);
    out.push('\n');

    // Order: models.rs, then the per-command structs, then the error types —
    // matching the order those files are read in when reasoning about drift.
    declare!(
        cfg,
        out,
        MemberRow,
        Member,
        MemberInput,
        PaymentMethod,
        Membership,
        DocumentKind,
        Document,
        DocumentInput,
        MemberDetail,
        Checkin,
        Filter,
    );
    declare!(
        cfg,
        out,
        RenewalPreview,
        EntryStatus,
        EntryCheck,
        CheckinRow,
        Dashboard,
        ExpiringDocument,
        ExpiryKind,
        Expiry,
    );
    declare!(cfg, out, Reason, AppError);

    out
}

fn bindings_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/bindings.ts")
}

#[test]
fn bindings_match_rust() {
    let generated = generate();
    let path = bindings_path();

    if std::env::var_os("UPDATE_BINDINGS").is_some() {
        std::fs::write(&path, &generated).expect("failed to write src/bindings.ts");
        return;
    }

    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    assert_eq!(
        generated, committed,
        "\n\nsrc/bindings.ts is out of date with the Rust structs it mirrors.\n\
         Run `UPDATE_BINDINGS=1 cargo test bindings` from src-tauri/ and commit the result.\n"
    );
}
