// AUTO-GENERATED by ts-rs — DO NOT EDIT BY HAND.
// Run `cargo test` in src-tauri/ to check this file for drift, or
// `UPDATE_BINDINGS=1 cargo test` from src-tauri/ to regenerate it.

export type MemberRow = { id: number, firstName: string, lastName: string, phone: string | null, email: string | null, joinedOn: string, 
/**
 * Last day currently paid for, or None if they have never had a membership.
 */
paidThrough: string | null, 
/**
 * Expiry of the newest health certificate on file, or None if there is none.
 */
certThrough: string | null, lastCheckin: string | null, };

export type Member = { id: number, firstName: string, lastName: string, nationalId: string | null, birthDate: string | null, phone: string | null, email: string | null, emergencyContact: string | null, emergencyPhone: string | null, notes: string | null, joinedOn: string, };

export type MemberInput = { firstName: string, lastName: string, nationalId: string | null, birthDate: string | null, phone: string | null, email: string | null, emergencyContact: string | null, emergencyPhone: string | null, notes: string | null, };

export type PaymentMethod = "cash" | "card" | "transfer";

export type Membership = { id: number, memberId: number, startsOn: string, endsOn: string, priceCents: number, paidCents: number, paymentMethod: PaymentMethod | null, note: string | null, createdAt: string, voidedAt: string | null, };

export type DocumentKind = "health_cert" | "id_card" | "waiver" | "contract" | "photo" | "receipt" | "other";

export type Document = { id: number, memberId: number | null, kind: DocumentKind, title: string | null, sha256: string, relPath: string, mime: string | null, bytes: number | null, originalName: string | null, issuer: string | null, issuedOn: string | null, expiresOn: string | null, addedAt: string, };

export type DocumentInput = { memberId: number, kind: DocumentKind, 
/**
 * Absolute path on disk of the file being imported; it is copied, not moved.
 */
sourcePath: string, title: string | null, issuer: string | null, issuedOn: string | null, expiresOn: string | null, };

export type MemberDetail = { member: Member, memberships: Array<Membership>, documents: Array<Document>, paidThrough: string | null, certThrough: string | null, };

export type Checkin = { id: number, memberId: number, at: string, membershipId: number | null, overrideReason: string | null, };

export type Filter = "all" | "active" | "expiring" | "expired" | "certExpired" | "certMissing";

export type RenewalPreview = { startsOn: string, endsOn: string, priceCents: number, 
/**
 * True when the member is still covered, so this period stacks on the end
 * of the current one rather than starting today.
 */
stacks: boolean, };

export type EntryStatus = "ok" | "warn" | "block";

export type EntryCheck = { memberId: number, firstName: string, lastName: string, paidThrough: string | null, certThrough: string | null, status: EntryStatus, 
/**
 * Translatable codes, never finished sentences — the frontend writes the
 * prose so the receptionist reads it in her own language.
 */
reasons: Array<Reason>, 
/**
 * Membership id that authorises entry, if any.
 */
membershipId: number | null, };

export type CheckinRow = { id: number, memberId: number, firstName: string, lastName: string, at: string, overrideReason: string | null, };

export type Dashboard = { gymName: string, currency: string, today: string, activeMembers: number, expiringSoon: number, expired: number, certExpired: number, certMissing: number, checkinsToday: number, };

export type ExpiringDocument = { id: number, memberId: number, firstName: string, lastName: string, kind: DocumentKind, expiresOn: string, };

export type ExpiryKind = "membership" | "certificate" | "certificate_missing";

export type Expiry = { memberId: number, firstName: string, lastName: string, phone: string | null, kind: ExpiryKind, date: string, 
/**
 * Negative once the date has passed.
 */
daysLeft: number, };

export type Reason = { code: string, params: { [key in string]: string }, };

export type AppError = { 
/**
 * Dotted identifier the frontend translates, e.g. `member.duplicate_id`.
 */
code: string, 
/**
 * English fallback, shown only when the catalogue lacks the code.
 */
message: string, 
/**
 * Values interpolated into the translated string.
 */
params: { [key in string]: string }, };

